cd ..
start cmd /c "mode con cols=45 lines=10 && title 1+8 && php index.php Book/Collect/content/id/1"
start cmd /c "mode con cols=45 lines=10 && title 2+8 && php index.php Book/Collect/content/id/2"
start cmd /c "mode con cols=45 lines=10 && title 3+8 && php index.php Book/Collect/content/id/3"
start cmd /c "mode con cols=45 lines=10 && title 4+8 && php index.php Book/Collect/content/id/4"
start cmd /c "mode con cols=45 lines=10 && title 5+8 && php index.php Book/Collect/content/id/5"
start cmd /c "mode con cols=45 lines=10 && title 6+8 && php index.php Book/Collect/content/id/6"
start cmd /c "mode con cols=45 lines=10 && title 7+8 && php index.php Book/Collect/content/id/7"
start cmd /c "mode con cols=45 lines=10 && title 8+8 && php index.php Book/Collect/content/id/8"
REM start cmd /c "mode con cols=45 lines=10 && title 9+16 && php index.php Book/Collect/content/id/9"
REM start cmd /c "mode con cols=45 lines=10 && title 10+16 && php index.php Book/Collect/content/id/10"
REM start cmd /c "mode con cols=45 lines=10 && title 11+16 && php index.php Book/Collect/content/id/11"
REM start cmd /c "mode con cols=45 lines=10 && title 12+16 && php index.php Book/Collect/content/id/12"
REM start cmd /c "mode con cols=45 lines=10 && title 13+16 && php index.php Book/Collect/content/id/13"
REM start cmd /c "mode con cols=45 lines=10 && title 14+16 && php index.php Book/Collect/content/id/14"
REM start cmd /c "mode con cols=45 lines=10 && title 15+16 && php index.php Book/Collect/content/id/15"
REM start cmd /c "mode con cols=45 lines=10 && title 16+16 && php index.php Book/Collect/content/id/16"